#!/usr/bin/env bash
# Re-run the CST validation for the 2peak design cases.
#
# For each case directory 2peak/<low>_<high> this drives
# Filter_CST_DataGen_Share/main.sh (--workflow 2peak) once per method and
# sweeps the requested incidence angles.  Existing CST output is moved to a
# timestamped backup instead of being overwritten, each attempt resumes from
# the angles that already finished, and failures are retried because Python
# and CST start-up on this machine crash intermittently.
#
# With --jobs N the cases are spread over N concurrent CST sessions.  Each
# worker gets a private copy of the CST project (only Model/ + ModelCache/,
# about 4 MB) because every run clears the project result folder, and gets a
# disjoint slice of the CPU list.
#
# Usage examples
#   ./run_2peak_cases.sh --dry-run                 # show what would run
#   ./run_2peak_cases.sh                           # all cases, cvae, 0/30/60
#   ./run_2peak_cases.sh --jobs 4                  # 4 concurrent CST sessions
#   ./run_2peak_cases.sh --angles "0 10 20 30 40 50 60"
#   ./run_2peak_cases.sh --methods "cvae tandem" --jobs 4
#   ./run_2peak_cases.sh --cases "430_620 500_600"

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
PEAK_ROOT="$REPO_ROOT/2peak"
MASTER_PROJECT="$SCRIPT_DIR/model2021_nk_model_multi_peaks.cst"

# Defaults ---------------------------------------------------------------
CASES=""
METHODS="cvae"
ANGLES="0 30 60"
JOBS=1
ATTEMPTS=5
RETRY_DELAY=20
CPU_LIST="${TANDEM_CPU_LIST:-0-7,12-31}"
PYTHON_BIN="${TANDEM_PYTHON:-/home/yuxiao/miniconda3/envs/pytorch/bin/python}"
LOG_DIR="$PEAK_ROOT/logs_cst"
WORK_ROOT="$SCRIPT_DIR/parallel_work"
DO_BACKUP=1
DRY_RUN=0
CLEAN_TEMP=0

usage() {
    sed -n '2,24p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
    exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --cases)       CASES="$2"; shift 2 ;;
        --methods)     METHODS="$2"; shift 2 ;;
        --angles)      ANGLES="$2"; shift 2 ;;
        --jobs)        JOBS="$2"; shift 2 ;;
        --attempts)    ATTEMPTS="$2"; shift 2 ;;
        --retry-delay) RETRY_DELAY="$2"; shift 2 ;;
        --cpu-list)    CPU_LIST="$2"; shift 2 ;;
        --python)      PYTHON_BIN="$2"; shift 2 ;;
        --log-dir)     LOG_DIR="$2"; shift 2 ;;
        --work-root)   WORK_ROOT="$2"; shift 2 ;;
        --clean-temp)  CLEAN_TEMP=1; shift ;;
        --no-backup)   DO_BACKUP=0; shift ;;
        --dry-run)     DRY_RUN=1; shift ;;
        -h|--help)     usage 0 ;;
        *) echo "Unknown option: $1" >&2; usage 1 ;;
    esac
done

[[ -x "$PYTHON_BIN" ]] || { echo "Python interpreter not found: $PYTHON_BIN" >&2; exit 1; }
command -v xvfb-run >/dev/null || { echo "xvfb-run is required." >&2; exit 1; }
[[ -f "$MASTER_PROJECT" ]] || { echo "CST project not found: $MASTER_PROJECT" >&2; exit 1; }
[[ "$JOBS" =~ ^[0-9]+$ && "$JOBS" -ge 1 ]] || { echo "--jobs must be a positive integer." >&2; exit 1; }

# Expand "0-7,12-31" into an array of individual CPU ids. ----------------
expand_cpu_list() {
    local spec="$1" chunk start end cpu
    local -a cpus=()
    IFS=',' read -ra parts <<<"$spec"
    for chunk in "${parts[@]}"; do
        if [[ "$chunk" == *-* ]]; then
            start="${chunk%%-*}"; end="${chunk##*-}"
            for ((cpu = start; cpu <= end; cpu++)); do cpus+=("$cpu"); done
        else
            cpus+=("$chunk")
        fi
    done
    printf '%s\n' "${cpus[@]}"
}

mapfile -t ALL_CPUS < <(expand_cpu_list "$CPU_LIST")
TOTAL_CPUS=${#ALL_CPUS[@]}
if [[ "$JOBS" -gt "$TOTAL_CPUS" ]]; then
    echo "--jobs ($JOBS) exceeds the ${TOTAL_CPUS} CPUs in --cpu-list." >&2
    exit 1
fi

# CPU slice for worker index $1 (0-based); contiguous, remainder spread out.
worker_cpu_list() {
    local index="$1"
    local base=$((TOTAL_CPUS / JOBS))
    local extra=$((TOTAL_CPUS % JOBS))
    local start=$((index * base + (index < extra ? index : extra)))
    local count=$((base + (index < extra ? 1 : 0)))
    local joined="" cpu
    for ((cpu = start; cpu < start + count; cpu++)); do
        joined+="${joined:+,}${ALL_CPUS[$cpu]}"
    done
    printf '%s' "$joined"
}

# Private CST project copy for worker index $1; echoes the .cst path.
prepare_worker_project() {
    local index="$1"
    if [[ "$JOBS" -eq 1 ]]; then
        printf '%s' "$MASTER_PROJECT"
        return
    fi
    local base_name project_dir worker_dir target
    base_name="$(basename "${MASTER_PROJECT%.cst}")"
    project_dir="${MASTER_PROJECT%.cst}"
    worker_dir="$WORK_ROOT/w$index"
    target="$worker_dir/$base_name.cst"

    rm -rf "$worker_dir"
    mkdir -p "$worker_dir/$base_name"
    cp "$MASTER_PROJECT" "$target"
    # Result/ and Temp/ are regenerated by the solver and are the only large
    # parts of the project, so they are deliberately not copied.
    local sub
    for sub in Model ModelCache Export SP; do
        [[ -d "$project_dir/$sub" ]] && cp -r "$project_dir/$sub" "$worker_dir/$base_name/"
    done
    printf '%s' "$target"
}

# Case discovery ---------------------------------------------------------
if [[ -z "$CASES" ]]; then
    CASES="$(cd "$PEAK_ROOT" && ls -d [0-9]*_[0-9]* 2>/dev/null | sort)"
fi
[[ -n "$CASES" ]] || { echo "No 2peak case directories found under $PEAK_ROOT." >&2; exit 1; }

# Build the (case, method) job list. -------------------------------------
JOB_LIST=()
for case_name in $CASES; do
    case_dir="$PEAK_ROOT/$case_name"
    if [[ ! -d "$case_dir" ]]; then
        echo "SKIP $case_name: no such directory $case_dir" >&2
        continue
    fi
    for method in $METHODS; do
        if [[ "$method" == "cvae" ]]; then
            structure_file="$case_dir/cvae/cvae_structure.txt"
        else
            structure_file="$case_dir/tandem/tandem_structure.txt"
        fi
        if [[ ! -f "$structure_file" ]]; then
            echo "SKIP $case_name/$method: missing $structure_file" >&2
            continue
        fi
        JOB_LIST+=("$case_name|$method")
    done
done
[[ ${#JOB_LIST[@]} -gt 0 ]] || { echo "Nothing to run." >&2; exit 1; }

mkdir -p "$LOG_DIR"
STAMP="$(date +%Y%m%d-%H%M%S)"
STATUS_DIR="$LOG_DIR/.status-$STAMP"
mkdir -p "$STATUS_DIR"

NUM_ANGLES="$(wc -w <<<"$ANGLES")"
echo "Repository root : $REPO_ROOT"
echo "Python          : $PYTHON_BIN"
echo "CPU affinity    : $CPU_LIST ($TOTAL_CPUS cpus)"
echo "Concurrent jobs : $JOBS"
echo "Methods         : $METHODS"
echo "Angles (deg)    : $ANGLES ($NUM_ANGLES per case)"
echo "Attempts/run    : $ATTEMPTS"
echo "Logs            : $LOG_DIR"
echo "Runs queued     : ${#JOB_LIST[@]} (${#JOB_LIST[@]} x $NUM_ANGLES solves)"
echo

if [[ "$CLEAN_TEMP" -eq 1 ]]; then
    temp_dir="${MASTER_PROJECT%.cst}/Temp"
    if [[ -d "$temp_dir" ]]; then
        echo "Clearing stale solver temp: $temp_dir ($(du -sh "$temp_dir" | cut -f1))"
        rm -rf "${temp_dir:?}"/*
    fi
fi

# One (case, method) run, with backup, resume and retries. ---------------
run_job() {
    local job="$1" project_file="$2" cpus="$3"
    local case_name="${job%%|*}" method="${job##*|}"
    local case_dir="$PEAK_ROOT/$case_name"
    local peak_low="${case_name%%_*}" peak_high="${case_name##*_}"
    local structure_file out_dir

    if [[ "$method" == "cvae" ]]; then
        structure_file="$case_dir/cvae/cvae_structure.txt"
        out_dir="$case_dir/cst"
    else
        structure_file="$case_dir/tandem/tandem_structure.txt"
        out_dir="$case_dir/cst_tandem"
    fi

    local cmd=(
        taskset -c "$cpus"
        env TANDEM_PYTHON="$PYTHON_BIN" MPLBACKEND=Agg
        "$SCRIPT_DIR/main.sh"
        --workflow 2peak
        --method "$method"
        --peak-wavelengths "$peak_low" "$peak_high"
        --structure-file "$structure_file"
        --output-dir "$out_dir"
        --cst-file "$project_file"
        --angles $ANGLES
    )

    if [[ "$DRY_RUN" -eq 1 ]]; then
        echo "[$case_name/$method] DRY RUN on cpus $cpus"
        echo "  ${cmd[*]} --dry-run"
        "${cmd[@]}" --dry-run | sed 's/^/  /'
        echo "ok" >"$STATUS_DIR/${case_name}_${method}"
        return 0
    fi

    if [[ "$DO_BACKUP" -eq 1 && -d "$out_dir" ]]; then
        echo "[$case_name/$method] backup -> ${out_dir}.bak-${STAMP}"
        mv "$out_dir" "${out_dir}.bak-${STAMP}"
    fi

    local log_file="$LOG_DIR/${case_name}_${method}_${STAMP}.log"
    local attempt resume_id
    for ((attempt = 1; attempt <= ATTEMPTS; attempt++)); do
        # Angles already exported here are skipped, so a retry continues
        # instead of re-solving finished angles.
        resume_id=0
        if [[ -d "$out_dir" ]]; then
            resume_id="$(find "$out_dir" -maxdepth 1 -name '[0-9][0-9][0-9][0-9][0-9].b' | wc -l)"
        fi
        echo "[$case_name/$method] attempt $attempt/$ATTEMPTS cpus=$cpus resume-id=$resume_id"
        if "${cmd[@]}" --resume-id "$resume_id" >>"$log_file" 2>&1; then
            echo "[$case_name/$method] OK"
            echo "ok" >"$STATUS_DIR/${case_name}_${method}"
            return 0
        fi
        # Separate a real input/validation error from the intermittent
        # Python/CST start-up crashes, which are worth retrying.
        if grep -qE '^(FileNotFoundError|ValueError):' "$log_file"; then
            echo "[$case_name/$method] real error, not retrying:"
            grep -E '^(FileNotFoundError|ValueError):' "$log_file" | tail -3 | sed 's/^/    /'
            break
        fi
        echo "[$case_name/$method] attempt failed, last log lines:"
        tail -5 "$log_file" | sed 's/^/    /'
        (( attempt < ATTEMPTS )) && sleep "$RETRY_DELAY"
    done

    echo "[$case_name/$method] FAILED (see $log_file)"
    echo "failed" >"$STATUS_DIR/${case_name}_${method}"
    return 1
}

# Dispatch: round-robin the jobs onto $JOBS sequential workers. -----------
worker_index=0
WORKER_PIDS=()
for ((worker_index = 0; worker_index < JOBS; worker_index++)); do
    worker_jobs=()
    for ((job_index = worker_index; job_index < ${#JOB_LIST[@]}; job_index += JOBS)); do
        worker_jobs+=("${JOB_LIST[$job_index]}")
    done
    [[ ${#worker_jobs[@]} -gt 0 ]] || continue

    worker_cpus="$(worker_cpu_list "$worker_index")"
    worker_project="$(prepare_worker_project "$worker_index")"
    echo "worker $worker_index: cpus=$worker_cpus project=$worker_project jobs=${worker_jobs[*]}"

    if [[ "$JOBS" -eq 1 ]]; then
        for job in "${worker_jobs[@]}"; do
            run_job "$job" "$worker_project" "$worker_cpus" || true
        done
    else
        (
            for job in "${worker_jobs[@]}"; do
                run_job "$job" "$worker_project" "$worker_cpus" || true
            done
        ) &
        WORKER_PIDS+=("$!")
    fi
done
echo

for pid in ${WORKER_PIDS[@]+"${WORKER_PIDS[@]}"}; do
    wait "$pid" || true
done

# Summary ----------------------------------------------------------------
echo "==================== summary ===================="
succeeded=0
failed=()
for job in "${JOB_LIST[@]}"; do
    case_name="${job%%|*}"; method="${job##*|}"
    if [[ "$(cat "$STATUS_DIR/${case_name}_${method}" 2>/dev/null)" == "ok" ]]; then
        succeeded=$((succeeded + 1))
    else
        failed+=("$case_name/$method")
    fi
done
echo "succeeded: $succeeded / ${#JOB_LIST[@]}"
if [[ ${#failed[@]} -gt 0 ]]; then
    echo "failed   : ${#failed[@]}"
    printf '  - %s\n' "${failed[@]}"
    exit 1
fi
echo "failed   : 0"
